module.exports = `SELECT X1.CLS_IDX, X1.CLS_SEQ, X1.STD_IDX, X1.CLS_ID, X1.ATTEND_YN
, X2.SBJ_CLS_IDX AS SBJ_CLS_IDX
, X2.SBJ_IDX AS SBJ_IDX
, STUD.STD_ID , X2.SBJ_CLS_IDX AS SBJ_CLS_IDX
, STUD.STD_ID
FROM (
SELECT A.CLS_IDX, A.STD_IDX, A.CLS_SEQ, A.ATTEND_YN, ICLS.CLS_ID
FROM HS_TB_CLS_ATTENDANCE A
	, HS_TB_CLASS_INFO ICLS
WHERE ICLS.CLS_IDX = A.CLS_IDX
AND RIGHT(ICLS.CLS_ID, 4) = (SELECT CODE_LV FROM HS_TB_COMMON_CODE WHERE CODE = 'CURRENT_TRIMESTER' AND DEL_FLAG = 'N')
AND A.DEL_FLAG = 'N'
AND ICLS.DEL_FLAG = 'N'
) X1
LEFT OUTER JOIN (
SELECT ECLS.STD_IDX, ECLS.SBJ_CLS_IDX, ICLS.CLS_IDX, ICLS.CLS_ID, MCRS.SBJ_IDX
FROM HS_TB_ENROLL_CLASS ECLS
	, HS_TB_SBJ_CLS_MAP MCLS, HS_TB_SBJ_COURSE_MAP MCRS, HS_TB_CLASS_INFO ICLS, HS_TB_COURSE_INFO ICRS
WHERE 1=1
AND MCLS.SBJ_CLS_IDX = ECLS.SBJ_CLS_IDX
AND MCLS.SBJ_COURSE_IDX = MCRS.SBJ_COURSE_IDX
AND ECLS.DEL_FLAG = 'N'
AND MCLS.DEL_FLAG = 'N'
AND MCRS.DEL_FLAG = 'N'
AND ICLS.CLS_IDX = MCLS.CLS_IDX
AND RIGHT(ICLS.CLS_ID, 4) = (SELECT CODE_LV FROM HS_TB_COMMON_CODE WHERE CODE = 'CURRENT_TRIMESTER' AND DEL_FLAG = 'N')
AND ICLS.DEL_FLAG = 'N'
AND ICRS.COURSE_IDX = MCRS.COURSE_IDX
AND ICRS.DEL_FLAG = 'N'
) X2 ON X1.STD_IDX = X2.STD_IDX AND X1.CLS_IDX = X2.CLS_IDX
LEFT OUTER JOIN HS_TB_STUDENT_INFO STUD ON STUD.STD_IDX = X1.STD_IDX
WHERE SBJ_CLS_IDX IS NULL
AND ATTEND_YN NOT IN ('N')
ORDER BY CLS_IDX, CLS_SEQ, STD_IDX`;